site_name: domdb
site_url: https://evidlabel.github.io/domdb/  # Update with your actual URL
repo_url: https://github.com/evidlabel/domdb
repo_name: evidlabel/domdb

theme:
  name: material
  palette:
    primary: black
    scheme: slate
  features:
    - content.code.copy
    - content.tabs
  font:
    text: Ubuntu
    code: Ubuntu Mono

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Output Example: output.md
  - Contributing: contributing.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            heading_level: 2
            show_root_heading: true
