name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install dependencies and run tests
      run: |
        uv venv .venv
        source .venv/bin/activate
        uv pip install .[dev]
        pytest

  # deploy-docs:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Python 3.12
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #     - name: Install uv
  #       run: |
  #         curl -LsSf https://astral.sh/uv/install.sh | sh
  #         echo "$HOME/.cargo/bin" >> $GITHUB_PATH

  #     - name: Install dependencies
  #       run: |
  #         uv venv .venv --seed
  #         source .venv/bin/activate
  #         uv pip install -e .[dev]

  #     - name: Build MkDocs site
  #       run: |
  #         source .venv/bin/activate
  #         uv run mkdocs build

  #     - name: Deploy to GitHub Pages
  #       uses: peaceiris/actions-gh-pages@v4
  #       with:
  #         personal_token: ${{ secrets.DEPLOY_TOKEN }}
  #         publish_dir: ./site
  #         force_orphan: true